### ISSUE TITLE
no queue 'xxxx' in vhost '/'

### ISSUE THREAD

**Issue by p-bizouard** [CentraleSupelec/aristote-dispatcher#2]
When the consumer started before Rabbitmq, it failed to initialize the queue :

```INFO:     10.2.1.19:59668 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiormq/abc.py", line 44, in __inner
    return await self.task
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sender.py", line 235, in proxy
    rpc_response = await rpc_client.call(priority, threshold, requested_model)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/sender.py", line 146, in call
    model_queue = await self.channel.get_queue(name=model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aio_pika/channel.py", line 375, in get_queue
    return await self.declare_queue(name=name, passive=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aio_pika/channel.py", line 350, in declare_queue
    await queue.declare(timeout=timeout)
  File "/usr/local/lib/python3.12/site-packages/aio_pika/queue.py", line 100, in declare
    self.declaration_result = await channel.queue_declare(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiormq/channel.py", line 858, in queue_declare
    return await self.rpc(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiormq/base.py", line 164, in wrap
    return await self.create_task(func(self, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiormq/abc.py", line 46, in __inner
    raise self._exception from e
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiormq/abc.py", line 46, in __inner
    raise self._exception from e
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 684, in _wrap_awaitable
    return await awaitable
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiormq/abc.py", line 46, in __inner
    raise self._exception from e
  File "/usr/local/lib/python3.12/site-packages/aiormq/channel.py", line 441, in _reader
    await hook(frame)
  File "/usr/local/lib/python3.12/site-packages/aiormq/channel.py", line 410, in _on_close_frame
    raise exc
aiormq.exceptions.ChannelNotFoundEntity: NOT_FOUND - no queue 'xxx' in vhost '/'
```

Temporary solution : restart the consumer

**Comment by p-bizouard** [comment]
Fixed in consumer latest update
